import { Page, expect } from '@playwright/test';

// Helper to fill UI forms for creating/editing entities

export async function createBuilding(
  page: Page,
  name: string,
  address: string = '123 Main St',
  floors: number = 3,
  units: number = 6,
  notes: string = 'Generated by automated test'
) {
  await page.goto('/buildings');
  await page.getByRole('button', { name: /add building/i }).click();

  await page.getByLabel('Building Name *').fill(name);
  await page.getByLabel('Address *').fill(address);
  await page.getByLabel('Number of Floors *').fill(String(floors));
  await page.getByLabel('Total Units *').fill(String(units));
  await page.getByLabel('Notes').fill(notes);

  await page.getByRole('button', { name: 'Add Building', exact: true }).click();
  await expect(page.getByText('Building added!')).toBeVisible();
}

export async function createRoom(
  page: Page,
  buildingName: string,
  roomNumber: string,
  floor: number = 1,
  type: 'single' | 'shared' = 'single',
  capacity: number = 1,
  rentAmount: number = 5000,
  status: 'vacant' | 'occupied' | 'maintenance' = 'vacant'
) {
  await page.goto('/rooms');
  await page.getByRole('button', { name: /add room/i }).click();

  // Select building
  await page.locator('label:has-text("Building *") + div button, label:has-text("Building *") + button').click();
  await page.getByRole('option', { name: buildingName }).click();

  await page.getByLabel('Room Number *').fill(roomNumber);
  await page.getByLabel('Floor *').fill(String(floor));

  // Type selection
  await page.locator('label:has-text("Room Type *") + div button, label:has-text("Room Type *") + button').click();
  await page.getByRole('option', { name: new RegExp(type, 'i') }).click();

  await page.getByLabel('Capacity *').fill(String(capacity));
  await page.getByLabel('Rent Amount (₹) *').fill(String(rentAmount));

  // Status selection
  await page.locator('label:has-text("Status *") + div button, label:has-text("Status *") + button').click();
  await page.getByRole('option', { name: new RegExp(status, 'i') }).click();

  await page.getByRole('button', { name: 'Add Room', exact: true }).click();
  await expect(page.getByText('Room added!')).toBeVisible();
}

export async function createTenant(
  page: Page,
  name: string,
  phone: string = '+91 9999988888',
  joinDate: string = new Date().toISOString().split('T')[0],
  buildingName: string,
  roomNumber: string,
  advancePaid: number = 10000,
  status: 'active' | 'inactive' = 'active'
) {
  await page.goto('/tenants');
  await page.getByRole('button', { name: /add tenant/i }).click();

  await page.getByLabel('Full Name *').fill(name);
  await page.getByLabel('Phone *').fill(phone);
  await page.getByLabel('Join Date *').fill(joinDate);

  // Select building
  await page.locator('label:has-text("Building *") + div button, label:has-text("Building *") + button').click();
  await page.getByRole('option', { name: buildingName }).click();

  // Select room
  await page.locator('label:has-text("Room *") + div button, label:has-text("Room *") + button').click();
  await page.getByRole('option', { name: new RegExp(`Room ${roomNumber}`, 'i') }).click();

  await page.getByLabel('Advance Paid (₹)').fill(String(advancePaid));

  // Status
  await page.locator('label:has-text("Status") + div button, label:has-text("Status") + button').click();
  await page.getByRole('option', { name: new RegExp(status, 'i') }).click();

  await page.getByRole('button', { name: 'Add Tenant', exact: true }).click();
  await expect(page.getByText('Tenant added!')).toBeVisible();
}

export async function createExpense(
  page: Page,
  buildingName: string,
  category: 'electricity' | 'water' | 'maintenance' | 'repair' | 'salary' | 'other',
  amount: number,
  date: string = new Date().toISOString().split('T')[0],
  description: string = 'Automated E2E Expense'
) {
  await page.goto('/expenses');
  await page.getByRole('button', { name: /add expense/i }).click();

  // Select building
  await page.locator('label:has-text("Building *") + div button, label:has-text("Building *") + button').click();
  await page.getByRole('option', { name: buildingName }).click();

  // Category
  await page.locator('label:has-text("Category *") + div button, label:has-text("Category *") + button').click();
  await page.getByRole('option', { name: new RegExp(category, 'i') }).click();

  await page.getByLabel('Amount (₹) *').fill(String(amount));
  await page.getByLabel('Date *').fill(date);
  await page.getByLabel('Description').fill(description);

  await page.getByRole('button', { name: 'Add Expense', exact: true }).click();
  await expect(page.getByText('Expense added!')).toBeVisible();
}

export async function createRentPayment(
  page: Page,
  tenantName: string,
  amount: number,
  month: number = new Date().getMonth() + 1,
  year: number = new Date().getFullYear(),
  status: 'paid' | 'unpaid' | 'partial' = 'paid',
  paidDate: string = new Date().toISOString().split('T')[0]
) {
  await page.goto('/rent');
  await page.getByRole('button', { name: /record payment/i }).click();

  // Select Tenant
  await page.locator('label:has-text("Tenant *") + div button, label:has-text("Tenant *") + button').click();
  await page.getByRole('option', { name: new RegExp(tenantName, 'i') }).click();

  // Month
  await page.locator('label:has-text("Month") + div button, label:has-text("Month") + button').click();
  await page.getByRole('option', { name: new RegExp(MONTH_NAMES[month - 1], 'i') }).click();

  await page.getByLabel('Year').fill(String(year));
  await page.getByLabel('Amount (₹)').fill(String(amount));

  // Status
  await page.locator('label:has-text("Status") + div button, label:has-text("Status") + button').click();
  await page.getByRole('option', { name: new RegExp(status, 'i') }).click();

  if (status === 'paid') {
    await page.getByLabel('Paid Date').fill(paidDate);
  }

  await page.getByRole('button', { name: 'Record', exact: true }).click();
  await expect(page.getByText('Payment recorded!')).toBeVisible();
}

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

/**
 * Cleanup helper that scans for any building card matching "E2E Building" or "IsolationTest"
 * and deletes them. Due to DB cascade constraints, this cleanly purges all cascade-related
 * rooms, tenants, payments, and expenses!
 */
export async function cleanupAllTestBuildings(page: Page) {
  await page.goto('/buildings');

  // Let the page load
  await page.waitForLoadState('networkidle');

  // Find all cards containing test markers
  const cards = page.locator('div.bg-white', {
    hasText: /(E2E Building|IsolationTest|TestBuilding|CRUDTest)/i
  });

  const count = await cards.count();
  for (let i = 0; i < count; i++) {
    // Refresh cards query to avoid stale element reference
    const activeCard = page.locator('div.bg-white', {
      hasText: /(E2E Building|IsolationTest|TestBuilding|CRUDTest)/i
    }).first();

    if (await activeCard.isVisible()) {
      // Open dropdown
      await activeCard.locator('button').first().click();
      
      // Click delete
      await page.getByRole('menuitem', { name: /delete/i }).click();
      
      // Confirm dialog
      await page.getByRole('button', { name: 'Confirm' }).click();
      
      // Wait for success toast
      await expect(page.getByText(/building deleted/i)).toBeVisible();
      
      // Tiny pause to let the UI react
      await page.waitForTimeout(500);
    }
  }
}
